CREATE TABLE users(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    xp NUMERIC DEFAULT 0,
    name TEXT NOT NULL,
    avatar TEXT DEFAULT 'https://image.flaticon.com/icons/svg/78/78373.svg'
);