CREATE TABLE users(
    id Integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    xp NUMERIC DEFAULT 0,
    name TEXT NOT NULL,
    xp_threshold NUMERIC DEFAULT 500,
    avatar URL NOT NULL,
    level INTEGER DEFAULT 1
);