CREATE TABLE squads(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    squad_name TEXT NOT NULL,
    squad_location TEXT NOT NULL,
    leader INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    capacity INTEGER NOT NULL
);
CREATE TABLE user_squads(
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    squad_id INTEGER REFERENCES squads(id) ON DELETE CASCADE NOT NULL
);
INSERT INTO squads (id, squad_name, squad_location, leader, capacity) VALUES
(999, 'General Chat', 'USA', 1, 9999);