CREATE TABLE chat(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    message_body VARCHAR(500) NOT NULL,
    time_stamp TIMESTAMP DEFAULT now() NOT NULL,
    pinned VARCHAR(500),
    squad_id INTEGER REFERENCES squads(id) ON DELETE CASCADE DEFAULT 999
);

CREATE FUNCTION expire_chat_deletion() RETURNS trigger
    LANGUAGE plpgsql
    AS $$

BEGIN
    DELETE FROM chat WHERE time_stamp < NOW() - INTERVAL '6 hours';
    RETURN NEW;
END;
$$;

CREATE TRIGGER expire_chat_deletion_trigger
    BEFORE INSERT OR UPDATE ON chat EXECUTE 
    PROCEDURE expire_chat_deletion();