CREATE TABLE chat(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    message_body VARCHAR(500) NOT NULL,
    time_stamp TIMESTAMP DEFAULT now() NOT NULL,
    pinned VARCHAR(500),
    squad_id INTEGER REFERENCES squads(id) ON DELETE CASCADE DEFAULT 999
);
INSERT INTO chat (user_id, message_body, squad_id) VALUES
(1, 'Welcome to Squad up', 999);